source 'http://rubygems.org'

gem 'activerecord', '6.1.7.1', :require => 'active_record'
gem 'database_cleaner'
gem 'pry'
gem 'pry-nav'
gem 'rack-test'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3', '~>1.3.6'
gem 'thin'
gem 'tux'
gem 'capybara'
gem 'bootstrap', '~> 4.4.1'
gem 'bcrypt' #transforming password
#gem 'activerecord-deprecated_finders', require: 'active_record/deprecated_finders'